### ISSUE TITLE
datetime parsing is broken in safari

### ISSUE THREAD

**Issue by ken210** [czanella/mapa-vacina#2]
The current datetime format `'2021-09-23 17:05:23.123'` parses as `Invalid Date` in Safari.

If we replace the space between date and time with a  `T` it should be fixed

so `'2021-09-23 17:05:23.123'` becomes `'2021-09-23T17:05:23.123'`

**Comment by czanella-remo** [comment]
Solved by https://github.com/czanella/mapa-vacina/commit/e1c45a25b7e2de5748ddf9db349646535ac47e87

**Comment by czanella** [comment]
Solved by https://github.com/czanella/mapa-vacina/commit/e1c45a25b7e2de5748ddf9db349646535ac47e87 .
